// <auto-generated />
using System;
using AwesomeCare.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AwesomeCare.DataAccess.Migrations
{
    [DbContext(typeof(AwesomeCareDbContext))]
    [Migration("20200322132008_tbl_StaffShiftBooking_ColumnChange")]
    partial class tbl_StaffShiftBooking_ColumnChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AwesomeCare.Model.Models.BaseRecordItemModel", b =>
                {
                    b.Property<int>("BaseRecordItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BaseRecordItemId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseRecordId")
                        .HasColumnName("BaseRecordId");

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnName("ValueName")
                        .HasMaxLength(225);

                    b.HasKey("BaseRecordItemId");

                    b.HasIndex("BaseRecordId");

                    b.ToTable("tbl_BaseRecordItem");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.BaseRecordModel", b =>
                {
                    b.Property<int>("BaseRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BaseRecordId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(255);

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnName("KeyName")
                        .HasMaxLength(50);

                    b.HasKey("BaseRecordId");

                    b.ToTable("tbl_BaseRecord");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnName("About")
                        .HasMaxLength(255);

                    b.Property<int>("AreaCodeId")
                        .HasColumnName("AreaCodeId");

                    b.Property<int>("CapacityId")
                        .HasColumnName("CapacityId");

                    b.Property<int>("ChoiceOfStaffId")
                        .HasColumnName("ChoiceOfStaffId");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnName("DateOfBirth")
                        .HasMaxLength(15);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("EndDate");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnName("Firstname")
                        .HasMaxLength(50);

                    b.Property<int>("GenderId")
                        .HasColumnName("GenderId");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnName("Hobbies")
                        .HasMaxLength(255);

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnName("IdNumber")
                        .HasMaxLength(50);

                    b.Property<string>("KeySafe")
                        .IsRequired()
                        .HasColumnName("KeySafe")
                        .HasMaxLength(50);

                    b.Property<string>("Keyworker")
                        .IsRequired()
                        .HasColumnName("Keyworker")
                        .HasMaxLength(50);

                    b.Property<int>("LanguageId")
                        .HasColumnName("LanguageId");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasColumnName("Middlename")
                        .HasMaxLength(50);

                    b.Property<int>("NumberOfCalls")
                        .HasColumnName("NumberOfCalls");

                    b.Property<int>("NumberOfStaff")
                        .HasColumnName("NumberOfStaff");

                    b.Property<string>("PassportFilePath")
                        .HasColumnName("PassportFilePath");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnName("PostCode")
                        .HasMaxLength(50);

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasColumnName("ProviderReference")
                        .HasMaxLength(50);

                    b.Property<string>("ProvisionVenue")
                        .IsRequired()
                        .HasColumnName("ProvisionVenue")
                        .HasMaxLength(50);

                    b.Property<decimal>("Rate")
                        .HasColumnName("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnName("ServiceId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("StartDate");

                    b.Property<int>("StatusId")
                        .HasColumnName("StatusId");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnName("Surname")
                        .HasMaxLength(50);

                    b.Property<string>("TeamLeader")
                        .IsRequired()
                        .HasColumnName("TeamLeader")
                        .HasMaxLength(50);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.Property<int>("TeritoryId")
                        .HasColumnName("TeritoryId");

                    b.Property<string>("UniqueId")
                        .HasColumnName("UniqueId");

                    b.HasKey("ClientId");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("tbl_Client");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientCareDetails", b =>
                {
                    b.Property<int>("ClientCareDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientCareDetailsId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientCareDetailsTaskId")
                        .HasColumnName("ClientCareDetailsTaskId");

                    b.Property<int>("ClientId")
                        .HasColumnName("ClientId");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Location")
                        .HasColumnName("Location")
                        .HasMaxLength(250);

                    b.Property<string>("Mitigation")
                        .HasColumnName("Mitigation")
                        .HasMaxLength(250);

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasMaxLength(250);

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnName("Risk")
                        .HasMaxLength(250);

                    b.HasKey("ClientCareDetailsId");

                    b.HasIndex("ClientCareDetailsTaskId");

                    b.HasIndex("ClientId");

                    b.ToTable("tbl_ClientCareDetails");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientCareDetailsHeading", b =>
                {
                    b.Property<int>("ClientCareDetailsHeadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientCareDetailsHeadingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnName("Heading")
                        .HasMaxLength(225);

                    b.HasKey("ClientCareDetailsHeadingId");

                    b.HasIndex("Heading")
                        .IsUnique()
                        .HasName("IX_tbl_ClientCareDetailsHeading_Heading");

                    b.ToTable("tbl_ClientCareDetailsHeading");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientCareDetailsTask", b =>
                {
                    b.Property<int>("ClientCareDetailsTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientCareDetailsTaskId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientCareDetailsHeadingId")
                        .HasColumnName("ClientCareDetailsHeadingId");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnName("Task")
                        .HasMaxLength(225);

                    b.HasKey("ClientCareDetailsTaskId");

                    b.HasIndex("ClientCareDetailsHeadingId");

                    b.ToTable("tbl_ClientCareDetailsTask");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientInvolvingParty", b =>
                {
                    b.Property<int>("ClientInvolvingPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientInvolvingPartyId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(225);

                    b.Property<int>("ClientId")
                        .HasColumnName("ClientId");

                    b.Property<int>("ClientInvolvingPartyItemId")
                        .HasColumnName("ClientInvolvingPartyItemId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasMaxLength(125);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnName("Relationship")
                        .HasMaxLength(50);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.HasKey("ClientInvolvingPartyId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientInvolvingPartyItemId");

                    b.ToTable("tbl_ClientInvolvingParty");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientInvolvingPartyItem", b =>
                {
                    b.Property<int>("ClientInvolvingPartyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientInvolvingPartyItemId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasMaxLength(225);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnName("ItemName")
                        .HasMaxLength(100);

                    b.HasKey("ClientInvolvingPartyItemId");

                    b.HasIndex("ItemName")
                        .IsUnique()
                        .HasName("IX_tbl_ClientInvolvingPartyItem_ItemName");

                    b.ToTable("tbl_ClientInvolvingPartyItem");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRegulatoryContact", b =>
                {
                    b.Property<int>("ClientRegulatoryContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientRegulatoryContactId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseRecordItemId")
                        .HasColumnName("BaseRecordItemId");

                    b.Property<int>("ClientId")
                        .HasColumnName("ClientId");

                    b.Property<DateTime?>("DatePerformed")
                        .HasColumnName("DatePerformed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnName("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .HasColumnName("Evidence");

                    b.HasKey("ClientRegulatoryContactId");

                    b.HasIndex("BaseRecordItemId");

                    b.HasIndex("ClientId");

                    b.ToTable("tbl_ClientRegulatoryContact");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRota", b =>
                {
                    b.Property<int>("ClientRotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientRotaId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnName("ClientId");

                    b.Property<int>("ClientRotaTypeId")
                        .HasColumnName("ClientRotaTypeId");

                    b.HasKey("ClientRotaId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientRotaTypeId");

                    b.ToTable("tbl_ClientRota");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRotaDays", b =>
                {
                    b.Property<int>("ClientRotaDaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientRotaDaysId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientRotaId")
                        .HasColumnName("ClientRotaId");

                    b.Property<int>("RotaDayofWeekId")
                        .HasColumnName("RotaDayofWeekId");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnName("StartTime")
                        .HasMaxLength(25);

                    b.Property<string>("StopTime")
                        .IsRequired()
                        .HasColumnName("StopTime")
                        .HasMaxLength(25);

                    b.HasKey("ClientRotaDaysId");

                    b.HasIndex("ClientRotaId");

                    b.HasIndex("RotaDayofWeekId");

                    b.ToTable("tbl_ClientRotaDays");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRotaTask", b =>
                {
                    b.Property<int>("ClientRotaTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientRotaTaskId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientRotaDaysId")
                        .HasColumnName("ClientRotaDaysId");

                    b.Property<int>("RotaTaskId")
                        .HasColumnName("RotaTaskId");

                    b.HasKey("ClientRotaTaskId");

                    b.HasIndex("ClientRotaDaysId");

                    b.HasIndex("RotaTaskId");

                    b.ToTable("tbl_ClientRotaTask");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRotaType", b =>
                {
                    b.Property<int>("ClientRotaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientRotaTypeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.Property<string>("RotaType")
                        .IsRequired()
                        .HasColumnName("RotaType")
                        .HasMaxLength(15);

                    b.HasKey("ClientRotaTypeId");

                    b.HasIndex("RotaType")
                        .IsUnique()
                        .HasName("IX_tbl_ClientRotaType_RotaType");

                    b.ToTable("tbl_ClientRotaType");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.CompanyContactModel", b =>
                {
                    b.Property<int>("CompanyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyContactId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("ContactEmail")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("ContactName")
                        .HasMaxLength(255);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("ContactTelephone")
                        .HasMaxLength(255);

                    b.HasKey("CompanyContactId");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("tbl_CompanyContact");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.CompanyModel", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(255);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("CompanyName")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasMaxLength(255);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnName("Language")
                        .HasMaxLength(255);

                    b.Property<string>("LogoUrl")
                        .HasColumnName("LogoUrl");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnName("Website")
                        .HasMaxLength(255);

                    b.HasKey("CompanyId");

                    b.ToTable("tbl_Company");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.Rota", b =>
                {
                    b.Property<int>("RotaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasColumnName("Area")
                        .HasMaxLength(225);

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnName("Gender")
                        .HasMaxLength(15);

                    b.Property<int>("NumberOfStaff")
                        .HasColumnName("NumberOfStaff");

                    b.Property<string>("RotaName")
                        .IsRequired()
                        .HasColumnName("RotaName")
                        .HasMaxLength(225);

                    b.HasKey("RotaId");

                    b.ToTable("tbl_ClientRotaName");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.RotaDayofWeek", b =>
                {
                    b.Property<int>("RotaDayofWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RotaDayofWeekId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DayofWeek")
                        .IsRequired()
                        .HasColumnName("DayofWeek")
                        .HasMaxLength(15);

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.HasKey("RotaDayofWeekId");

                    b.ToTable("tbl_RotaDayofWeek");

                    b.HasData(
                        new { RotaDayofWeekId = 1, DayofWeek = "Monday", Deleted = false },
                        new { RotaDayofWeekId = 2, DayofWeek = "Tuesday", Deleted = false },
                        new { RotaDayofWeekId = 3, DayofWeek = "Wednesday", Deleted = false },
                        new { RotaDayofWeekId = 4, DayofWeek = "Thursday", Deleted = false },
                        new { RotaDayofWeekId = 5, DayofWeek = "Friday", Deleted = false },
                        new { RotaDayofWeekId = 6, DayofWeek = "Saturday", Deleted = false },
                        new { RotaDayofWeekId = 7, DayofWeek = "Sunday", Deleted = false }
                    );
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.RotaTask", b =>
                {
                    b.Property<int>("RotaTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RotaTaskId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnName("Deleted");

                    b.Property<string>("GivenAcronym")
                        .IsRequired()
                        .HasColumnName("GivenAcronym")
                        .HasMaxLength(50);

                    b.Property<string>("NotGivenAcronym")
                        .IsRequired()
                        .HasColumnName("NotGivenAcronym")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasMaxLength(125);

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnName("TaskName")
                        .HasMaxLength(125);

                    b.HasKey("RotaTaskId");

                    b.HasIndex("GivenAcronym")
                        .IsUnique()
                        .HasName("IX_tbl_RotaTask_GivenAcronym");

                    b.HasIndex("NotGivenAcronym")
                        .IsUnique()
                        .HasName("IX_tbl_RotaTask_NotGivenAcronym");

                    b.HasIndex("TaskName")
                        .IsUnique()
                        .HasName("IX_tbl_RotaTask_TaskName");

                    b.ToTable("tbl_RotaTask");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ShiftBooking", b =>
                {
                    b.Property<int>("ShiftBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ShiftBookingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DriverRequired")
                        .HasColumnName("DriverRequired");

                    b.Property<int>("NumberOfStaff")
                        .HasColumnName("NumberOfStaff");

                    b.Property<int?>("PublishTo")
                        .HasColumnName("PublishTo");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnName("Remark")
                        .HasMaxLength(225);

                    b.Property<int>("Rota")
                        .HasColumnName("Rota");

                    b.Property<string>("ShiftDate")
                        .IsRequired()
                        .HasColumnName("ShiftDate")
                        .HasMaxLength(15);

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnName("StartTime")
                        .HasMaxLength(15);

                    b.Property<string>("StopTime")
                        .IsRequired()
                        .HasColumnName("StopTime")
                        .HasMaxLength(15);

                    b.Property<int>("Team")
                        .HasColumnName("Team_StaffPersonalInfoId");

                    b.HasKey("ShiftBookingId");

                    b.ToTable("tbl_ShiftBooking");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffCommunication", b =>
                {
                    b.Property<int>("StaffCommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffCommunicationId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnName("ActionTaken")
                        .HasMaxLength(255);

                    b.Property<string>("Attachment")
                        .HasColumnName("Attachment");

                    b.Property<int>("CommunicationClassId")
                        .HasColumnName("CommunicationClass");

                    b.Property<string>("Concern")
                        .IsRequired()
                        .HasColumnName("Concern")
                        .HasMaxLength(500);

                    b.Property<string>("ExpectedAction")
                        .IsRequired()
                        .HasColumnName("ExpectedAction")
                        .HasMaxLength(255);

                    b.Property<int>("PersonInvolved")
                        .HasColumnName("PersonInvolved");

                    b.Property<int>("PersonResponsibleForAction")
                        .HasColumnName("PersonResponsibleForAction");

                    b.Property<int>("Status")
                        .HasColumnName("Status");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ValueDate")
                        .HasColumnName("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StaffCommunicationId");

                    b.ToTable("tbl_StaffCommunication");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffEducation", b =>
                {
                    b.Property<int>("StaffEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffEducationId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(255);

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnName("Certificate")
                        .HasMaxLength(125);

                    b.Property<string>("CertificateAttachment")
                        .HasColumnName("CertificateAttachment");

                    b.Property<string>("EndDate")
                        .HasColumnName("EndDate")
                        .HasMaxLength(25);

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnName("Institution")
                        .HasMaxLength(255);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnName("Location")
                        .HasMaxLength(255);

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnName("StartDate")
                        .HasMaxLength(25);

                    b.HasKey("StaffEducationId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffEducation");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffEmergencyContact", b =>
                {
                    b.Property<int>("StaffEmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffEmergencyContactId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(100);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnName("ContactName")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnName("Relationship")
                        .HasMaxLength(50);

                    b.Property<int>("StaffPersonalInfoId");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.HasKey("StaffEmergencyContactId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffEmergencyContact");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffPersonalInfo", b =>
                {
                    b.Property<int>("StaffPersonalInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffPersonalInfoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutMe")
                        .HasColumnName("AboutMe")
                        .HasMaxLength(225);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(225);

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnName("CV");

                    b.Property<string>("CanDrive")
                        .IsRequired()
                        .HasColumnName("CanDrive")
                        .HasMaxLength(3);

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnName("CoverLetter");

                    b.Property<string>("DBS")
                        .IsRequired()
                        .HasColumnName("DBS")
                        .HasMaxLength(3);

                    b.Property<string>("DBSAttachment")
                        .HasColumnName("DBSAttachment");

                    b.Property<DateTime?>("DBSExpiryDate")
                        .HasColumnName("DBSExpiryDate");

                    b.Property<string>("DBSUpdateNo")
                        .HasColumnName("DBSUpdateNo")
                        .HasMaxLength(50);

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnName("DateOfBirth")
                        .HasMaxLength(50);

                    b.Property<string>("DrivingLicense")
                        .HasColumnName("DrivingLicense");

                    b.Property<DateTime?>("DrivingLicenseExpiryDate")
                        .HasColumnName("DrivingLicenseExpiryDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasMaxLength(225);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("EndDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnName("Gender")
                        .HasMaxLength(7);

                    b.Property<string>("Hobbies")
                        .HasColumnName("Hobbies")
                        .HasMaxLength(225);

                    b.Property<string>("IdNumber")
                        .HasColumnName("IdNumber")
                        .HasMaxLength(50);

                    b.Property<string>("Keyworker")
                        .HasColumnName("Keyworker")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasColumnName("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("NI")
                        .IsRequired()
                        .HasColumnName("NI")
                        .HasMaxLength(3);

                    b.Property<string>("NIAttachment")
                        .HasColumnName("NIAttachment");

                    b.Property<DateTime?>("NIExpiryDate")
                        .HasColumnName("NIExpiryDate");

                    b.Property<string>("Passcode")
                        .HasColumnName("Passcode")
                        .HasMaxLength(15);

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnName("PostCode")
                        .HasMaxLength(50);

                    b.Property<string>("ProfilePix")
                        .IsRequired()
                        .HasColumnName("ProfilePix");

                    b.Property<decimal?>("Rate")
                        .HasColumnName("Rate");

                    b.Property<string>("RegistrationId")
                        .HasColumnName("RegistrationId")
                        .HasMaxLength(20);

                    b.Property<string>("RightToWork")
                        .IsRequired()
                        .HasColumnName("RightToWork")
                        .HasMaxLength(3);

                    b.Property<string>("RightToWorkAttachment")
                        .HasColumnName("RightToWorkAttachment");

                    b.Property<DateTime?>("RightToWorkExpiryDate")
                        .HasColumnName("RightToWorkExpiryDate");

                    b.Property<string>("Self_PYE")
                        .IsRequired()
                        .HasColumnName("Self_PYE")
                        .HasMaxLength(3);

                    b.Property<string>("Self_PYEAttachment")
                        .HasColumnName("Self_PYEAttachment");

                    b.Property<int?>("StaffWorkTeamId")
                        .HasColumnName("StaffWorkTeamId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .HasColumnName("Status");

                    b.Property<string>("TeamLeader")
                        .HasColumnName("TeamLeader")
                        .HasMaxLength(50);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.Property<string>("WorkTeam")
                        .HasColumnName("WorkTeam")
                        .HasMaxLength(50);

                    b.HasKey("StaffPersonalInfoId");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasName("IX_tbl_StaffPersonalInfo_RegistrationId")
                        .HasFilter("[RegistrationId] IS NOT NULL");

                    b.HasIndex("StaffWorkTeamId");

                    b.ToTable("tbl_StaffPersonalInfo");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffPersonalInfoComment", b =>
                {
                    b.Property<int>("StaffPersonalInfoCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffPersonalInfoCommentId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnName("Comment")
                        .HasMaxLength(250);

                    b.Property<int?>("CommentBy_UserId")
                        .HasColumnName("CommentBy_UserId");

                    b.Property<DateTime>("CommentOn")
                        .HasColumnName("CommentOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.HasKey("StaffPersonalInfoCommentId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffPersonalInfoComment");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffReferee", b =>
                {
                    b.Property<int>("StaffRefereeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffRefereeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasMaxLength(255);

                    b.Property<string>("Attachment")
                        .HasColumnName("Attachment");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("CompanyName")
                        .HasMaxLength(125);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasMaxLength(125);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasMaxLength(50);

                    b.Property<string>("PositionofReferee")
                        .IsRequired()
                        .HasColumnName("PositionofReferee")
                        .HasMaxLength(25);

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnName("Referee")
                        .HasMaxLength(125);

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.HasKey("StaffRefereeId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffReferee");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffRegulatoryContact", b =>
                {
                    b.Property<int>("StaffRegulatoryContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffRegulatoryContactId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseRecordItemId")
                        .HasColumnName("BaseRecordItemId");

                    b.Property<DateTime?>("DatePerformed")
                        .HasColumnName("DatePerformed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnName("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .HasColumnName("Evidence");

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.HasKey("StaffRegulatoryContactId");

                    b.HasIndex("BaseRecordItemId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffRegulatoryContact");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffShiftBooking", b =>
                {
                    b.Property<int>("StaffShiftBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffShiftBookingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RotaId");

                    b.Property<int>("ShiftBookingId")
                        .HasColumnName("ShiftBookingId");

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.HasKey("StaffShiftBookingId");

                    b.HasIndex("RotaId");

                    b.HasIndex("ShiftBookingId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffShiftBooking");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffShiftBookingDay", b =>
                {
                    b.Property<int>("StaffShiftBookingDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffShiftBookingDayId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnName("Day")
                        .HasMaxLength(2);

                    b.Property<int>("StaffShiftBookingId")
                        .HasColumnName("StaffShiftBookingId");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .HasColumnName("WeekDay")
                        .HasMaxLength(15);

                    b.HasKey("StaffShiftBookingDayId");

                    b.HasIndex("StaffShiftBookingId");

                    b.ToTable("tbl_StaffShiftBookingDay");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffTraining", b =>
                {
                    b.Property<int>("StaffTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffTrainingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnName("Certificate")
                        .HasMaxLength(125);

                    b.Property<string>("CertificateAttachment")
                        .HasColumnName("CertificateAttachment");

                    b.Property<string>("ExpiredDate")
                        .HasColumnName("ExpiredDate")
                        .HasMaxLength(25);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnName("Location")
                        .HasMaxLength(255);

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnName("StartDate")
                        .HasMaxLength(25);

                    b.Property<string>("Trainer")
                        .IsRequired()
                        .HasColumnName("Trainer")
                        .HasMaxLength(125);

                    b.Property<string>("Training")
                        .IsRequired()
                        .HasColumnName("Training")
                        .HasMaxLength(255);

                    b.HasKey("StaffTrainingId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.ToTable("tbl_StaffTraining");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffWorkTeam", b =>
                {
                    b.Property<int>("StaffWorkTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StaffWorkTeamId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WorkTeam")
                        .IsRequired()
                        .HasColumnName("WorkTeam");

                    b.HasKey("StaffWorkTeamId");

                    b.ToTable("tbl_StaffWorkTeam");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.Untowards", b =>
                {
                    b.Property<int>("UntowardsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UntowardsId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionRequired")
                        .IsRequired()
                        .HasColumnName("ActionRequired")
                        .HasMaxLength(225);

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasColumnName("ActionStatus")
                        .HasMaxLength(7);

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnName("ActionTaken")
                        .HasMaxLength(225);

                    b.Property<string>("Attachment")
                        .HasColumnName("Attachment");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnName("Date")
                        .HasMaxLength(15);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnName("Details")
                        .HasMaxLength(225);

                    b.Property<string>("ExpectedDateAndTimeOfFeedback")
                        .IsRequired()
                        .HasColumnName("ExpectedDateAndTimeOfFeedback")
                        .HasMaxLength(50);

                    b.Property<string>("FinalActionToCloseCase")
                        .HasColumnName("FinalActionToCloseCase")
                        .HasMaxLength(225);

                    b.Property<int>("HomeCareClientId")
                        .HasColumnName("HomeCareClientId");

                    b.Property<string>("HospitalEntryReason")
                        .HasColumnName("HospitalEntryReason")
                        .HasMaxLength(225);

                    b.Property<string>("HospitalExitDetails")
                        .HasColumnName("HospitalExitDetails")
                        .HasMaxLength(225);

                    b.Property<bool>("IsBlackListRequired")
                        .HasColumnName("IsBlackListRequired");

                    b.Property<bool>("IsHospitalEntry")
                        .HasColumnName("IsHospitalEntry");

                    b.Property<bool>("IsHospitalExit")
                        .HasColumnName("IsHospitalExit");

                    b.Property<string>("Others")
                        .HasColumnName("Others")
                        .HasMaxLength(225);

                    b.Property<string>("PersonReporting")
                        .HasColumnName("PersonReporting")
                        .HasMaxLength(100);

                    b.Property<string>("PersonReportingEmail")
                        .HasColumnName("PersonReportingEmail")
                        .HasMaxLength(225);

                    b.Property<string>("PersonReportingTelephone")
                        .HasColumnName("PersonReportingTelephone")
                        .HasMaxLength(50);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnName("Priority")
                        .HasMaxLength(7);

                    b.Property<bool>("ShouldNotifyInvolvingStaff")
                        .HasColumnName("ShouldNotifyInvolvingStaff");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnName("Subject")
                        .HasMaxLength(225);

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnName("TicketNumber")
                        .HasMaxLength(50);

                    b.Property<string>("TimeOfCall")
                        .IsRequired()
                        .HasColumnName("TimeOfCall")
                        .HasMaxLength(15);

                    b.Property<int>("TypeofRequiredNotification")
                        .HasColumnName("TypeofRequiredNotification");

                    b.HasKey("UntowardsId");

                    b.ToTable("tbl_Untowards");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.UntowardsOfficerToAct", b =>
                {
                    b.Property<int>("UntowardsOfficerToActId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UntowardsOfficerToActId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.Property<int>("UntowardsId")
                        .HasColumnName("UntowardsId");

                    b.HasKey("UntowardsOfficerToActId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.HasIndex("UntowardsId");

                    b.ToTable("tbl_UntowardsOfficerToAct");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.UntowardsStaffInvolved", b =>
                {
                    b.Property<int>("UntowardsStaffInvolvedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UntowardsStaffInvolvedId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StaffPersonalInfoId")
                        .HasColumnName("StaffPersonalInfoId");

                    b.Property<int>("UntowardsId")
                        .HasColumnName("UntowardsId");

                    b.HasKey("UntowardsStaffInvolvedId");

                    b.HasIndex("StaffPersonalInfoId");

                    b.HasIndex("UntowardsId");

                    b.ToTable("tbl_UntowardsStaffInvolved");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.BaseRecordItemModel", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.BaseRecordModel", "BaseRecord")
                        .WithMany("BaseRecordItems")
                        .HasForeignKey("BaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientCareDetails", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.ClientCareDetailsTask", "ClientCareDetailsTask")
                        .WithMany("ClientCareDetails")
                        .HasForeignKey("ClientCareDetailsTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.Client", "Client")
                        .WithMany("ClientCareDetails")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientCareDetailsTask", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.ClientCareDetailsHeading", "ClientCareDetailsHeading")
                        .WithMany("ClientCareDetailsTasks")
                        .HasForeignKey("ClientCareDetailsHeadingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientInvolvingParty", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.Client", "Client")
                        .WithMany("InvolvingParties")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.ClientInvolvingPartyItem", "ClientInvolvingPartyItem")
                        .WithMany("ClientInvolvingParty")
                        .HasForeignKey("ClientInvolvingPartyItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRegulatoryContact", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.BaseRecordItemModel", "BaseRecordItem")
                        .WithMany()
                        .HasForeignKey("BaseRecordItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.Client", "Client")
                        .WithMany("RegulatoryContact")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRota", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.Client", "Client")
                        .WithMany("ClientRota")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.ClientRotaType", "ClientRotaType")
                        .WithMany("ClientRota")
                        .HasForeignKey("ClientRotaTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRotaDays", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.ClientRota", "ClientRota")
                        .WithMany("ClientRotaDays")
                        .HasForeignKey("ClientRotaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.RotaDayofWeek", "RotaDayofWeek")
                        .WithMany("ClientRotaDays")
                        .HasForeignKey("RotaDayofWeekId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.ClientRotaTask", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.ClientRotaDays", "ClientRotaDays")
                        .WithMany("ClientRotaTask")
                        .HasForeignKey("ClientRotaDaysId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.RotaTask", "RotaTask")
                        .WithMany("ClientRotaTask")
                        .HasForeignKey("RotaTaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.CompanyContactModel", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.CompanyModel", "Company")
                        .WithOne("CompanyContact")
                        .HasForeignKey("AwesomeCare.Model.Models.CompanyContactModel", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffEducation", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "Staff")
                        .WithMany("Education")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffEmergencyContact", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffPersonalInfo", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffWorkTeam", "StaffWorkTeam")
                        .WithMany("StaffPersonalInfo")
                        .HasForeignKey("StaffWorkTeamId");
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffPersonalInfoComment", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany("StaffPersonalInfoComments")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffReferee", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "Staff")
                        .WithMany("References")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffRegulatoryContact", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.BaseRecordItemModel", "BaseRecordItem")
                        .WithMany()
                        .HasForeignKey("BaseRecordItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany("RegulatoryContact")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffShiftBooking", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.Rota")
                        .WithMany("ShiftBookings")
                        .HasForeignKey("RotaId");

                    b.HasOne("AwesomeCare.Model.Models.ShiftBooking", "ShiftBooking")
                        .WithMany("StaffShiftBooking")
                        .HasForeignKey("ShiftBookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany("ShiftBookings")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffShiftBookingDay", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffShiftBooking", "ShiftBooking")
                        .WithMany("Days")
                        .HasForeignKey("StaffShiftBookingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.StaffTraining", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "Staff")
                        .WithMany("Trainings")
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.UntowardsOfficerToAct", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany()
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.Untowards", "Untowards")
                        .WithMany("OfficerToAct")
                        .HasForeignKey("UntowardsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AwesomeCare.Model.Models.UntowardsStaffInvolved", b =>
                {
                    b.HasOne("AwesomeCare.Model.Models.StaffPersonalInfo", "StaffPersonalInfo")
                        .WithMany()
                        .HasForeignKey("StaffPersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AwesomeCare.Model.Models.Untowards", "Untowards")
                        .WithMany("StaffInvolved")
                        .HasForeignKey("UntowardsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
